- name: setup Mysql with db and remote login
  hosts: dev
  vars:
  vars_files:
    - vars.yaml
  tasks:
    - name: Make a directory
      file:
        path: /opt/mysql
        state: directory
        mode: '777'
        #- name: Copy mysql File
        #copy: src=mysql80-community-release-el7-7.noarch.rpm dest=/opt/mysql
      #when: "{{ inventory_hostname == 'node3' }}"

    - name: install mysql repo
      yum:
        name: /opt/mysql/mysql80-community-release-el7-7.noarch.rpm
        state: latest
    - name: install mysql
      yum:
        name: mysql-community-server
        state: latest
        disable_gpg_check: yes
    - name: Mysql service started
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Change mysql root password and keep track in
      shell: |
        password_match=`awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'`
        echo $password_match
        mysql -uroot -p$password_match --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ db_pass }}'; flush privileges; "
        echo "[client]"
        user=root
        password="{{ db_pass }}" > /root/.my.cnf
      args:
        creates: /root/.my.cnf
      register: change_temp_pass
      notify: restart mysqld

    - meta: flush_handlers
    - debug:
        var: change_temp_pass

    - name: set mysql host '%' for remote previledge
      shell: |
        pass='{{ db_pass }}'
        mysql -uroot -p$pass -e "CREATE USER 'saddam'@'192.168.20.180' IDENTIFIED WITH mysql_native_password BY '{{ db_pass }}'; ALTER USER 'saddam'@'192.168.20.180' IDENTIFIED WITH mysql_native_password BY '{{ db_pass }}'; GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'saddam'@'192.168.20.180' WITH GRANT OPTION; FLUSH PRIVILEGES; "
    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/my.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - restart mysqld

  handlers:
    - name: restart mysqld
      service:
        name: mysqld
        state: restarted
