---
- name: Pacakge installtion 
  hosts: nodes
  tasks:
    - block:
        - name: Show message
          debug:
            msg: "Trying HTTPD"
        - name: Install wrong package
          yum:
            name: httpd-wrong
            state: latest
      rescue:
        - name: show error
          debug:
            msg: "Unkonw package"
        - name: Install nginx
          yum:
            name: nginx
            state: present
      always:
        - name: message
          debug: 
            msg: "playbook done"
